"""Adds pigment spectrum and name

Revision ID: b030940723f5
Revises: 1f0d06bec59e
Create Date: 2018-03-25 23:16:21.537814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b030940723f5'
down_revision = '1f0d06bec59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pigments', sa.Column('name', sa.String(), nullable=True))
    op.add_column('pigments', sa.Column('spectrum', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pigments', 'spectrum')
    op.drop_column('pigments', 'name')
    # ### end Alembic commands ###
